version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
# permissions:
#   - object: /home/ubuntu/IMS_Ref/codedeploy
#     pattern: "*.sh"
#     owner: root
#     group: root
#     mode: 755
#     type:
#       - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 500
  # AfterInstall:
  #   - location: codedeploy/after_install.sh
  #     timeout: 500
  # ApplicationStart:
  #   - location: codedeploy/app_restart.sh
  #     timeout: 500
